name:                eve-cli
version:             0.1.0.0
github:              "ChrisPenner/eve-cli"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ChrisPenner/eve-cli#readme>

dependencies:
- base >= 4.7 && < 5
- eve >= 0.1.8 && < 0.2
- vty >= 5.20 && < 6
- lens >= 4.16.1 && < 4.17
- mtl >= 2.2.2 && < 2.3
- bytestring >= 0.10.8.2 && < 0.10.9
- text

library:
  source-dirs: src

executables:
  eve-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eve-cli

tests:
  eve-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eve-cli
